export const boxcar = {
  work: {
    company: "Boxcar - Solucoes Alternativas de Transport",
    position: "Mechanical Designer",
    country: "Brazil",
    from: "04/2008",
    to: "01/2010",
    logo: "boxcar.jpg",
    description: [
      "I joined Boxcar as the company’s first technical employee and the fifth overall, working directly under Sergio Kozemekin — a former Volkswagen logistics leader and one of the company’s partners at the time. Though he was my boss, Sergio became a mentor whose influence shaped my professional career from 2008 to 2014. In this role, I was tasked with designing the company’s first products and developing the facility layout from the ground up.",
    ],
    contributions: [
      "Designed and patented two models of small trailers from scratch, benchmarking market products to guide development.",
      "Built and managed the project’s design library, streamlining future product development and reducing redundant work.",
      "Planned and designed jigs and fixtures for welding and assembling, ensuring reliable manufacturing processes.",
      "Created a spreadsheet to monitor and control project development, tracking costs, processes, lead-times, and suppliers.",
      "Supervised prototype construction, testing performance and functionality to validate designs.",
      "Prepared detailed reports and specifications for product certification and presented them to regulatory authorities.",
      "Planned and supervised the implementation of the facility layout, optimizing workflow and supporting scalable production.",
    ],
    images: [
      { file: "boxcar-01.jpg", alt: "Boxcar trailer concept by Jeison" },
      { file: "boxcar-02.jpg", alt: "Boxcar trailer concept by Jeison" },
      { file: "boxcar-03.jpg", alt: "Boxcar trailer concept by Jeison" },
      { file: "boxcar-04.jpg", alt: "Boxcar trailer prototype by Jeison" },
      { file: "boxcar-05.jpg", alt: "Boxcar trailer prototype by Jeison" },
      { file: "boxcar-06.jpg", alt: "Boxcar trailer final product by Jeison" },
      { file: "boxcar-07.jpg", alt: "Boxcar trailer final product by Jeison" },
      { file: "boxcar-08.jpg", alt: "Boxcar trailer larger concept by Jeison" },
      { file: "boxcar-09.jpg", alt: "Boxcar ATV trailer by Jeison" },
      { file: "boxcar-10.jpg", alt: "Boxcar ATV trailer by Jeison" },
      { file: "boxcar-11.jpg", alt: "Boxcar ATV trailer by Jeison" },
      { file: "boxcar-12.jpg", alt: "Boxcar ATV trailer box and Jeison" },
      { file: "boxcar-13.jpg", alt: "Boxcar ATV trailer box and Jeison" },
      { file: "boxcar-14.jpg", alt: "Boxcar ATV trailer by Jeison" },
      { file: "boxcar-15.jpg", alt: "Boxcar trailer prototypes by Jeison" },
      { file: "boxcar-16.jpg", alt: "Boxcar open trailer concept by Jeison" },
      { file: "boxcar-17.jpg", alt: "Boxcar open trailer concept by Jeison" },
    ],
  },
}
